# Generated by Django 5.0.1 on 2024-01-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
