# Generated by Django 5.0.1 on 2024-01-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='api/')),
                ('fecha', models.DateField(max_length=10)),
                ('propietario', models.CharField(max_length=100)),
            ],
        ),
    ]
