# Generated by Django 4.2.4 on 2024-01-23 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_archivo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario'),
        ),
    ]
