# Generated by Django 4.2.4 on 2024-01-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_archivo_fecha_alter_archivo_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
