# Generated by Django 4.2.4 on 2024-01-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usuario_apellidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='nombre',
            field=models.CharField(default=2, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivo',
            name='peso',
            field=models.IntegerField(default=0),
        ),
    ]
