# Generated by Django 4.2.4 on 2024-01-24 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_archivo_nombre_archivo_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='peso',
        ),
    ]
