# Generated by Django 4.2.4 on 2024-01-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_archivo_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='nombre',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
